---
kind: pipeline
type: docker
name: default

platform:
  os: linux
  arch: amd64

steps:
  - name: test
    image: python:3.7-alpine
    commands:
      - apk add --no-cache mariadb-dev g++
      - pip install --upgrade pip pipenv
      - pipenv install --dev
      - pipenv run flake8
      - pipenv run flask db upgrade
      - pipenv run pytest -svv -p no:warnings
      - python -c "import config;import os;print('latest'+(','+config.VERSION if 'DRONE_TAG' in os.environ else ''))" > .tags
      - cat .tags
  - name: release-docker
    image: plugins/docker
    settings:
      username: jakewalker
      password:
        from_secret: docker_password
      repo: jakewalker/vh7