database = "sqlite:///data.db"

[auth]
url = "http://localhost:9001"
algorithms = ["RS256"]
audience = "vh7"
issuer = "vh7.uk"
user_info_endpoint = "{this.auth.url}/oauth2/userinfo"

[instance]
url = "http://localhost:8000"
app_url = "http://localhost:3000"
admin = "admin@localhost"

[uploads]
min_age = 30
max_age = 90
max_size = 256
folder = "./uploads/"
