"""Switch to word links.

Revision ID: bce812ae17b3
Revises: 1ff078c1cafb
Create Date: 2021-01-08 17:06:26.904440
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bce812ae17b3'
down_revision = '1ff078c1cafb'
branch_labels = None
depends_on = None


def upgrade():
    """Upgrade the database from the previous version."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shortlink', schema=None) as batch_op:
        batch_op.add_column(sa.Column('link', sa.String(), nullable=True))
        batch_op.create_index(batch_op.f('ix_shortlink_link'), ['link'],
                              unique=True)

    # ### end Alembic commands ###


def downgrade():
    """Downgrade the database to the previous version."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shortlink', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_shortlink_link'))
        batch_op.drop_column('link')

    # ### end Alembic commands ###
