name: ci
on:
  - push
  - pull_request
jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.8]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v1
        with:
          python-version: ${{ matrix.python }}
      - name: Install pipenv
        run: pip install pipenv
      - name: Install dependencies
        run: pipenv install --system --dev
      # - name: Type checking
      #   run: mypy main.py
      - name: Lint
        run: flake8

  release:
    runs-on: ubuntu-latest
    needs: ci
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build & Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v5.2
        with:
          image: jakewalker/vh7
          tags: latest,v1
          registry: docker.io
          username: jakewalker
          password: ${{ secrets.DOCKER_PASSWORD }}
